import * as esbuild from 'esbuild';
import * as fs from 'fs';
import * as path from 'path';

async function main() {
    const result = await esbuild.build({
        platform: 'neutral',
        entryPoints: [path.resolve(__dirname, './src/index.ts')],
        bundle: true,
        minify: false,
        target: ['es2020'],
        write: false,
        mainFields: ['browser', 'module', 'jsnext', 'main'],
        conditions: ['browser', 'import', 'production'],
        define: {},
    });

    const code = result.outputFiles[0].text;
    await fs.promises.writeFile(
        path.resolve(__dirname, './index.ts'),
        `/* File autogenerated */     
export const stdlibCode = ${JSON.stringify(code)};`
    );
}

main().then(
    () => {
        process.exit(0);
    },
    (error) => {
        console.error(error.stack || error);
        process.exit(1);
    }
);
