import * as api from '@gitbook/api';

import { version } from '../package.json';

/**
 * Generate the event to track in Segment for an actual GitBook event.
 */
export function generateSegmentTrackEvent(event: api.SiteViewEvent) {
    const { visitor, referrer, url, siteId } = event;

    const anonymousId = getAnonymousId(event);
    const visitedURL = new URL(url);
    return {
        event: '[GitBook] site_view',
        anonymousId,
        context: {
            library: {
                name: 'GitBook',
                version,
            },
            page: {
                path: visitedURL.pathname,
                search: visitedURL.search,
                url,
                referrer,
            },
            userAgent: visitor.userAgent,
            ip: visitor.ip,
        },
        properties: {
            siteId,
        },
    };
}

/**
 * Return the anonymous ID we send to Segment in the Track event.
 *
 * Retrieve the value from the `ajs_anonymous_id` Segment cookie if present.
 * This allows to consolidate the track event with other events generated by an anonymous user
 * that already has visited the customer website (where Segment tracking is setup).
 *
 * When there is no `ajs_anonymous_id` cookie, we fallback to using the GitBook anonymous ID.
 */
function getAnonymousId(event: api.SiteViewEvent): string {
    const { visitor } = event;
    const cookies = visitor.cookies;

    return cookies.ajs_anonymous_id || visitor.anonymousId;
}
