name: Setup 1Password CLI
description: Install 1Password CLI
inputs:
    OP_SERVICE_ACCOUNT_TOKEN:
        description: Service account token for 1Password
        required: true
runs:
    using: 'composite'
    steps:
        - name: Install 1Password CLI
          shell: bash
          run: curl -sSfo op.zip
              https://cache.agilebits.com/dist/1P/op2/pkg/v2.31.1/op_linux_amd64_v2.31.1.zip
              && unzip -od /usr/local/bin/ op.zip
              && rm op.zip
        - name: Setup 1Password CLI
          shell: bash
          run: op user get --me
          env:
              OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }}
