name: CI - Untrusted PR (Fork Safe)

on:
    pull_request:
        # This workflow runs on all PRs, including from forks
        # It only runs jobs that don't require secrets

jobs:
    test:
        runs-on: ubuntu-latest
        name: Test
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: 'package.json'
            - name: Install dependencies
              run: bun install --frozen-lockfile
            - name: Run tests
              run: bun run test

    format:
        runs-on: ubuntu-latest
        name: Format
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: 'package.json'
            - name: Install dependencies
              run: bun install --frozen-lockfile
            - name: Format
              run: bun run format:check

    typecheck:
        runs-on: ubuntu-latest
        name: Typecheck
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: 'package.json'
            - name: Install dependencies
              run: bun install --frozen-lockfile
            - name: Typecheck
              run: bun run typecheck

    build:
        runs-on: ubuntu-latest
        name: Build
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: 'package.json'
            - name: Install dependencies
              run: bun install --frozen-lockfile
            - name: Build
              run: bun run build
    check-limited:
        runs-on: ubuntu-latest
        name: Check integrations (limited)
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: 'package.json'
            - name: Install dependencies
              run: bun install --frozen-lockfile
            - name: Build
              run: bun run build
            - name: Check integrations (without external API calls)
              run: |
                  echo "Running limited integration check (no external API calls)"                  
                  test -d packages/adaptive/dist &&
                  test -d packages/api/dist &&
                  test -d packages/cli/dist &&
                  test -d packages/document/dist &&
                    echo "Build artifacts exist"
